<script lang="ts">
  import logo from '../assets/logo.svg'
  import { faEyeSlash } from '@fortawesome/free-solid-svg-icons'
  import Fa from 'svelte-fa'

  let showInstructionsModal = false
  let showErrorInfoModal = false

  if (!localStorage.getItem(`instructions-viewed`)) {
    showInstructionsModal = true
    localStorage.setItem(`instructions-viewed`, 'true')
  }
</script>

<div class="navbar mb-2 shadow-lg bg-neutral rounded-box">
  <div class="invisible w-0 px-0 mx-0 sm:visible sm:w-auto sm:px-2 sm:mx-2 min-h-inherit">
    <a class="min-h-inherit" href="https://github.com/Geomitron/Bridge">
      <img class="min-h-inherit p-0 sm:p-2" src={logo} alt="Bridge" />
    </a>
  </div>
  <div class="flex-1 px-2 mx-2">
    <span class="text-2xl font-bold">
      Error Viewer
    </span>
  </div>
  <div class="link link-accent m-4" on:click="{ () => showErrorInfoModal = true }">How errors are generated</div>
  <div class="link link-accent m-4" on:click="{ () => showInstructionsModal = true }">Instructions for charters</div>
</div>

<div id="error-info-modal" class="modal" class:modal-open={showErrorInfoModal}>
  <div class="modal-box !max-w-4xl max-h-screen overflow-y-auto">
    <h2 class="card-title font-bold">How errors are generated</h2>
    <p>These errors are generated by comparing the charts in the Google Drive folders on Chorus against the Chorus/Bridge rules and guidelines and against other charts available on Chorus and Bridge.</p>
    <br>
    <ul class="list-disc list-inside">
      <div><strong>Chorus/Bridge rules and guidelines:</strong></div>
      <li>These rules and guidelines can be found in <a class="link" target="_blank" href="https://docs.google.com/document/d/1XrLKnpL0xawaC90M4lLnhqhExwXM_3JpJnzNqlB_agM">this document</a>.</li>
      <li>Some rules are based on Clone Hero's expected chart format.</li>
      <li>Some rules are based on the charting community's standards and best practices.</li>
      <li>Some rules are to ensure credit is given to charters and that charts are uploaded only with the charter's permission.</li>
      <li>The goal is to ensure a consistent level of quality for charts that can be found on these platforms.</li>
      <br>
      <div><strong>Other charts available on Chorus and Bridge:</strong></div>
      <li>Corrections for the song name, artist, album, genre, or year are usually done by comparing the metadata of different charts of the same song.
        If one of these is different from the others, the "correct" one is chosen using a combination of manual and automatic educated guesses, so expect some corrections to be wrong.</li>
      <li>Corrections can be wrong if the wrong value was chosen, both options were correct (e.g. a song was on multiple albums), or if the scan incorrectly marked two different songs as being the same song.
        I will fix any such issues if they are brought to my attention. (Geo#8488 on Discord)</li>
      <br>
      This website will continue to be updated as new songs are scanned and old charts are updated. Errors that get fixed should eventually get automatically removed from this list.
    </ul>
    <div class="modal-action">
      <label for="error-info-modal" class="btn" on:click="{ () => showErrorInfoModal = false }">OK</label>
    </div>
  </div>
</div>

<div id="disclaimer-modal" class="modal" class:modal-open={showInstructionsModal}>
  <div class="modal-box !max-w-4xl max-h-screen overflow-y-auto">
    <h2 class="card-title font-bold">Instructions for charters (please read this)</h2>
    <ul class="list-disc list-inside">
      <div><strong>How to interpret each error in this list:</strong></div>
      <li>If you don't understand why it's listed here, <a class="link" target="_blank" href="https://docs.google.com/document/d/1XrLKnpL0xawaC90M4lLnhqhExwXM_3JpJnzNqlB_agM">this document</a> describes the formatting rules and guidelines.</li>
      <li>If you think it shouldn't be listed here, it's a bug or a mistake, so please let me know on Discord (Geo#8488) so I can fix it. <strong>(Fixing this is important; it's likely that another chart has incorrect metadata instead)</strong></li>
      <li>Warnings are probably not issues, but you should still read them to make sure. (hide them by clicking the <Fa class="inline-block mx-1 !align-middle" icon={faEyeSlash}/> icon)</li>
      <li>If you have charts in more than one source, errors for those charts will be divided across the different error lists.</li>
      <div class="divider"></div>
      <div><strong>Other things you should do:</strong></div>
      <li>On the main page, search for your charter name to see all the sources that include charts made by you.
        Let me know if there's a missing source or if your chart was put in a source without your permission.</li>
      <li> If you've made charts under different usernames/aliases, they should appear in the charter list grouped and separated by forward slashes.
        If that's not the case, let me know so I can fix it. (this lets Bridge show all your charts if someone searches by any of those usernames)</li>
    </ul>
    <br>
    <p>Note: Soon I will be releasing a program you can run to automatically fix "optimization errors". When it's done, I will replace this line with a link to it. (I'm hoping to finish it in the next week or two)</p>
    <div class="modal-action">
      <label for="disclaimer-modal" class="btn" on:click="{ () => showInstructionsModal = false }">OK</label>
    </div>
  </div>
</div>

<style>
  .min-h-inherit {
    min-height: inherit;
  }
</style>
